"""Added is_active field to user table

Revision ID: 5539a3bcc20e
Revises: 7c1831c3c446
Create Date: 2025-02-17 16:51:33.851255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5539a3bcc20e'
down_revision = '7c1831c3c446'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###
